import { courseLayout } from "../components/course-layout.js";
import { asset } from "../lib/assets.js";
import { escapeHtml } from "../lib/html.js";
import { keyPoints } from "../data/curriculum.js";
export function courseDetails(course) {
  return courseLayout(
    course,
    "about",
    `<div class="course-prose"><h2>Description</h2>${course.baseId === "digital" ? `<p>Embark on an enlightening exploration into the world of digital creation with our comprehensive course, “Build Digital Assets: A Comprehensive Guide.” This transformative learning experience invites you to delve deep into the intricacies of crafting impactful digital content. From laying the groundwork with foundational concepts to mastering advanced techniques, this guide is meticulously curated to empower you with the skills essential for navigating the dynamic landscape of digital asset creation.</p><p>In the initial modules, you’ll establish a solid foundation by immersing yourself in the foundational concepts that form the backbone of digital asset creation. Understand the fundamental elements that constitute compelling digital content and gain proficiency in leveraging these elements to communicate effectively in the digital realm.</p><p>As you progress through the course, you’ll ascend to higher levels of expertise, diving into the nuances of design principles that drive impactful creations. Uncover the secrets behind effective visual communication, exploring color theory, typography, and layout strategies that elevate your digital assets to new heights. Engage in hands-on exercises that reinforce your understanding, allowing you to apply these principles in practical scenarios.</p>` : `<p>${escapeHtml(course.description)}</p><p>Build your skills with a guided introduction, practical exercises, and a project you can add to your portfolio. Explore the lesson notes to get a feel for the course, and visit the creator profile to discover related topics.</p><p>This demo course uses the supplied digital-creation curriculum as a sample learning experience. Complete a lesson exercise and track your progress on this device.</p>`}<h2>Sneak Peak</h2><div class="course-gallery">${["sketch", "laptop", "design", "mobile"].map((name, i) => `<button data-gallery="${name}" aria-label="View project preview ${i + 1}"><img src="${asset("preview-" + name + ".webp")}" width="180" height="126" alt="${["Sketching a digital interface", "Design work on a laptop", "Digital design workspace", "Mobile interface designs"][i]}" loading="lazy"/></button>`).join("")}</div><h2>Key Points</h2><ul class="benefits course-key-points">${keyPoints.map((point) => `<li>${point}</li>`).join("")}</ul></div>`,
  );
}
