import { icon } from "./icons.js";
import { escapeHtml } from "../lib/html.js";
export function catalogToolbar() {
  return `<div class="catalog-toolbar"><div class="toolbar-filters"><button class="outline-control" data-filter-panel aria-expanded="false" aria-controls="catalog-filter-panel">${icon("filter")} Filter</button><label class="outline-control">${icon("bars")}<span class="sr-only">Course level</span><select name="level" aria-label="Course level"><option value="">Level</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label class="outline-control">${icon("design")}<span class="sr-only">Course category</span><select name="category" aria-label="Course category"><option value="">Category</option>${["Design", "Development", "Business", "Marketing", "Photography", "Data Science", "Finance"].map((c) => `<option>${c}</option>`).join("")}</select></label></div><label class="outline-control">${icon("sort")}<span class="sr-only">Sort courses</span><select name="sort" aria-label="Sort courses"><option value="relevance">Most relevant</option><option value="rating">Highest rated</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option><option value="title">Title: A to Z</option></select></label></div>
  <form class="catalog-filter-panel" id="catalog-filter-panel" hidden><label>Maximum price <select name="price" aria-label="Maximum price"><option value="">Any price</option><option value="25">$25 or less</option><option value="35">$35 or less</option></select></label><label>Minimum rating <select name="rating" aria-label="Minimum rating"><option value="">Any rating</option><option value="4.7">4.7 and up</option><option value="4.8">4.8 and up</option></select></label><button type="button" class="text-button" data-catalog-reset>Reset filters</button></form>`;
}
export function categoryChips() {
  return `<div class="catalog-chips" aria-label="Filter by topic">${["Featured", "Music", "Drawing & Painting", "Marketing", "Animation", "Social Media", "UI/UX Design", "Creative Marketing", "Cooking"].map((c) => `<button class="filter ${c === "Featured" ? "is-active" : ""}" data-catalog-category="${escapeHtml(c)}" aria-pressed="${c === "Featured"}">${c}</button>`).join("")}</div>`;
}
